# CMake generated Testfile for 
# Source directory: /home/jagen31/Robotics/HotTarget
# Build directory: /home/jagen31/Robotics/HotTarget
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(BlueBall1 "/src/run" "blueball" "/home/jagen31/Robotics/HotTarget/images/ballOnChair.jpg")
SET_TESTS_PROPERTIES(BlueBall1 PROPERTIES  FAIL_REGULAR_EXPRESSION "blue ball finder not found")
ADD_TEST(BlueBall2 "/src/run" "blueball" "/home/jagen31/Robotics/HotTarget/images/balls.jpg")
SET_TESTS_PROPERTIES(BlueBall2 PROPERTIES  FAIL_REGULAR_EXPRESSION "blue ball finder not found")
ADD_TEST(BlueBall3 "/src/run" "blueball" "/home/jagen31/Robotics/HotTarget/images/blueball.jpg")
SET_TESTS_PROPERTIES(BlueBall3 PROPERTIES  FAIL_REGULAR_EXPRESSION "blue ball finder not found")
ADD_TEST(RedBalls1 "/src/run" "redball" "/home/jagen31/Robotics/HotTarget/images/balls.jpg")
SET_TESTS_PROPERTIES(RedBalls1 PROPERTIES  FAIL_REGULAR_EXPRESSION "red ball finder not found")
ADD_TEST(RedBalls2 "/src/run" "redball" "/home/jagen31/Robotics/HotTarget/images/balls3.jpg")
SET_TESTS_PROPERTIES(RedBalls2 PROPERTIES  FAIL_REGULAR_EXPRESSION "red ball finder not found")
ADD_TEST(HorizontalTarget1 "/src/run" "horiztarget" "/home/jagen31/Robotics/HotTarget/images/FRC.jpg")
SET_TESTS_PROPERTIES(HorizontalTarget1 PROPERTIES  FAIL_REGULAR_EXPRESSION "horiz target finder not found")
ADD_TEST(HorizontalTarget2 "/src/run" "horiztarget" "/home/jagen31/Robotics/HotTarget/images/image.jpg")
SET_TESTS_PROPERTIES(HorizontalTarget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "horiz target finder not found")
ADD_TEST(HorizontalTarget3 "/src/run" "horiztarget" "/home/jagen31/Robotics/HotTarget/images/image4.jpg")
SET_TESTS_PROPERTIES(HorizontalTarget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "horiz target finder not found")
ADD_TEST(HorizontalTarget4 "/src/run" "horiztarget" "/home/jagen31/Robotics/HotTarget/images/target1.jpg")
SET_TESTS_PROPERTIES(HorizontalTarget4 PROPERTIES  FAIL_REGULAR_EXPRESSION "horiz target finder not found")
ADD_TEST(HorizontalTarget5 "/src/run" "horiztarget" "/home/jagen31/Robotics/HotTarget/images/target2.jpg")
SET_TESTS_PROPERTIES(HorizontalTarget5 PROPERTIES  FAIL_REGULAR_EXPRESSION "horiz target finder not found")
ADD_TEST(VerticalTarget1 "/src/run" "verttarget" "/home/jagen31/Robotics/HotTarget/images/FRC.jpg")
SET_TESTS_PROPERTIES(VerticalTarget1 PROPERTIES  FAIL_REGULAR_EXPRESSION "vertical target finder not found")
ADD_TEST(VerticalTarget2 "/src/run" "verttarget" "/home/jagen31/Robotics/HotTarget/images/image.jpg")
SET_TESTS_PROPERTIES(VerticalTarget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "vertical target finder not found")
ADD_TEST(VerticalTarget3 "/src/run" "verttarget" "/home/jagen31/Robotics/HotTarget/images/image4.jpg")
SET_TESTS_PROPERTIES(VerticalTarget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "vertical target finder not found")
ADD_TEST(VerticalTarget4 "/src/run" "verttarget" "/home/jagen31/Robotics/HotTarget/images/target1.jpg")
SET_TESTS_PROPERTIES(VerticalTarget4 PROPERTIES  FAIL_REGULAR_EXPRESSION "vertical target finder not found")
ADD_TEST(VerticalTarget5 "/src/run" "verttarget" "/home/jagen31/Robotics/HotTarget/images/target2.jpg")
SET_TESTS_PROPERTIES(VerticalTarget5 PROPERTIES  FAIL_REGULAR_EXPRESSION "vertical target finder not found")
SUBDIRS(src)
SUBDIRS(images)
